name = "Mingw"
version = "11.0.0"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Mingw"
lazy = "false"
src_version = "11.0.1"
platform = "x86_64-w64-mingw32"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:0a8f464fe8cd93e584d514db086dbccac5219d5f"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:a77226f464f192ea83663e80eaacc842a8bf6e9c400932c41fc146fa56f637dc"
        url = "https://github.com/JuliaBinaryWrappers/Mingw_jll.jl/releases/download/v11.0.0/Mingw-build_log-v11.0.0-x86_64-w64-mingw32.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c4aca9b5c801cd5a214cb4efaddcc8fb4bf0d92e"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:67933941dfb61d8f10cd26ea21cfdb1f8316577fe8054b62105c2ce281958c84"
        url = "https://github.com/JuliaBinaryWrappers/Mingw_jll.jl/releases/download/v11.0.0/Mingw-extract_log-v11.0.0-x86_64-w64-mingw32.tar.gz"

    [[builds.products]]
    name = "libmsvcrt_a"
    type = "file"
    path = "usr/lib/libmsvcrt.a"

    [[builds.sources]]
    treehash = "sha1:fc05e1af7513b31119bb9cb45f1c4efafc4901b1"
    url = "https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v11.0.1.tar.bz2"

    [builds.artifact]
    treehash = "sha1:cdec265c08afe9044eadc8c9a0d9ecdff93d84f5"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:951af63a93dde47ae2e6970e2790c4ed3cee59087e423c464dda83a62ba38f16"
        url = "https://github.com/JuliaBinaryWrappers/Mingw_jll.jl/releases/download/v11.0.0/Mingw-v11.0.0-x86_64-w64-mingw32.tar.gz"
[[builds]]
deps = []
name = "Mingw"
lazy = "false"
src_version = "11.0.1"
platform = "i686-w64-mingw32"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:e13e5ef9194f8a4590bc994bce6544de64409886"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ad19f01ac00ff9d407cd38b245bb4a9427a0a4743abe56e11057acde8fdb4a5e"
        url = "https://github.com/JuliaBinaryWrappers/Mingw_jll.jl/releases/download/v11.0.0/Mingw-build_log-v11.0.0-i686-w64-mingw32.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4ea3b0989436795c855d255185ebf83b51dac769"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:9aa1eeb74f47563c7c7f463a566309b70e286e30ff33210a9301d04e4e80ac03"
        url = "https://github.com/JuliaBinaryWrappers/Mingw_jll.jl/releases/download/v11.0.0/Mingw-extract_log-v11.0.0-i686-w64-mingw32.tar.gz"

    [[builds.products]]
    name = "libmsvcrt_a"
    type = "file"
    path = "usr/lib/libmsvcrt.a"

    [[builds.sources]]
    treehash = "sha1:fc05e1af7513b31119bb9cb45f1c4efafc4901b1"
    url = "https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v11.0.1.tar.bz2"

    [builds.artifact]
    treehash = "sha1:91a2a2b769f2208c59346e62808c70a73b45ef40"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:a6b66e7e4148d144b06b6e9eff3891c43fc465f58c6880c3c65db8958896dfbb"
        url = "https://github.com/JuliaBinaryWrappers/Mingw_jll.jl/releases/download/v11.0.0/Mingw-v11.0.0-i686-w64-mingw32.tar.gz"
